---
# Order Producer Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-producer
  namespace: default
  labels:
    app: order-producer
    version: 1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-producer
  template:
    metadata:
      labels:
        app: order-producer
        version: 1.0.0
    spec:
      containers:
      - name: order-producer
        image: order-services/order-producer:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
---
# Order Producer Service
apiVersion: v1
kind: Service
metadata:
  name: order-producer-service
  namespace: default
  labels:
    app: order-producer
spec:
  type: LoadBalancer
  selector:
    app: order-producer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
# Order Processor Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: default
  labels:
    app: order-processor
    version: 1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processor
  template:
    metadata:
      labels:
        app: order-processor
        version: 1.0.0
    spec:
      containers:
      - name: order-processor
        image: order-services/order-processor:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3